### ISSUE TITLE
Naming collision detected

### ISSUE THREAD

**Issue by flyingmate** [reqshark/react-native-hyperscript#1]
Hi, I'm using this library but whenever I install npm packages using 'npm install',
I get this error below. I have to remove the react-native folder and react-tools folder
under the react-native-hyperscript/node_modules folder to make js-bundle server start.
After deleting those folders, it works fine. I hope if it's possible not to generate those folders
while installing hyperscript. 

Thank you 

Bundle js server error ----

Error: Naming collision detected: /Users/james/Dropbox/Development/react/Builder/node_modules/react-native-hyperscript/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js collides with /Users/james/Dropbox/Development/react/Builder/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js
    at HasteMap._updateHasteMap (/Users/james/Dropbox/Development/react/Builder/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/HasteMap.js:123:13)
    at /Users/james/Dropbox/Development/react/Builder/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/HasteMap.js:95:28
    at tryCallOne (/Users/james/Dropbox/Development/react/Builder/node_modules/promise/lib/core.js:37:12)
    at /Users/james/Dropbox/Development/react/Builder/node_modules/promise/lib/core.js:103:15
    at flush (/Users/james/Dropbox/Development/react/Builder/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
Process terminated. Press <enter> to close the window

**Comment by reqshark** [comment]
hmm, that's interesting what version of react-native are you using?

**Comment by flyingmate** [comment]
Hi, I'm not using react-native currently, I forgot about the issue :) I am closing this issue. 
Thank you anyway

**Comment by reqshark** [comment]
ok thanks! :)
